# .det-tools/specs/master_commands.yaml
---
meta:
  version: "2.0.0"
  last_updated: "2025-09-29"
  purpose: "Master reference for all deterministic GitHub operations"

# Define reusable fragments
definitions:
  retry_policy: &standard_retry
    max_attempts: 3
    backoff: exponential
    backoff_base_seconds: 2
    timeout_seconds: 30

  output_schema: &standard_output
    format: json
    location: ".det-tools/out/"
    required: true

# All commands
commands:
  - name: gh-checkpoint
    version: "2.0.0"
    category: core

    purpose: "Atomic save point - commits and syncs current state to remote"

    # When to use this vs alternatives
    replaces:
      - "git add + git commit + git push"
      - "manual branch syncing"

    interface:
      parameters:
        - name: context
          type: string
          required: false
          description: "Checkpoint context message"
          examples:
            - "workstream-complete"
            - "validation-passed"

        - name: branch
          type: string
          required: false
          default: "HEAD"
          pattern: "^[a-zA-Z0-9/_-]+$"

      outputs:
        - path: ".det-tools/out/checkpoint.json"
          schema:
            type: object
            required_fields:
              - commit_sha
              - timestamp
              - branch_name
              - files_changed
          <<: *standard_output

      exit_codes:
        0: 
          status: success
          description: "Checkpoint created and synced"
        1:
          status: error
          description: "Working directory not clean"
          recovery: "Stash or commit changes first"
        2:
          status: error
          description: "Remote sync failed"
          recovery: "Check network and retry"

    implementation:
      bash: "./scripts/gh_checkpoint.sh"
      powershell: "./scripts/GH-Checkpoint.ps1"

    behavior:
      idempotent: true
      retryable: true
      rollback_safe: true
      parallel_safe: false  # Can't checkpoint same branch concurrently

    dependencies:
      requires:
        - git_repo_initialized
        - git_remote_configured
      conflicts:
        - gh-rollback  # Don't rollback during checkpoint

    retry: *standard_retry

    observability:
      metrics:
        - checkpoint_duration_ms
        - files_changed_count
        - commit_size_bytes
      audit_fields:
        - commit_sha
        - branch_name
        - files_modified
        - author

    # Critical notes for AI/humans
    notes: |
      IMPORTANT: This command uses --force-with-lease, not --force.
      Safe to call multiple times on same state (idempotent).
      Always run after validation passes to create recovery point.

    examples:
      - description: "Checkpoint after workstream completion"
        command: "gh-checkpoint --context 'workstream-a-complete'"
        expected_output: "checkpoint.json with commit SHA"

      - description: "Checkpoint specific branch"
        command: "gh-checkpoint --context 'integration-ready' --branch feature/x"
        expected_output: "checkpoint.json with branch ref"

    # Version history
    changelog:
      - version: "2.0.0"
        date: "2025-09-29"
        changes:
          - "Added --branch parameter"
          - "Switched to --force-with-lease"
      - version: "1.0.0"
        date: "2025-01-15"
        changes:
          - "Initial implementation"

  # Next command...
  - name: gh-init-workspace
    # ... same structure ...

  - name: gh-sync-remote
    # ... same structure ...

# Pipelines that use these commands
pipelines:
  - name: fast-path
    commands_used:
      - gh-checkpoint
      - gh-workstream
      - gh-release

  - name: parallel-with-train
    commands_used:
      - gh-checkpoint
      - gh-merge-workstreams
      - gh-merge-train

# Command relationships (helps AI understand dependencies)
relationships:
  - from: gh-init-workspace
    to: gh-checkpoint
    type: prerequisite
    description: "Must initialize workspace before checkpointing"

  - from: gh-checkpoint
    to: gh-sync-remote
    type: often_precedes
    description: "Checkpoint often called before sync"
