title = "CLI_RESTART gitleaks configuration"

[allowlist]
description = "Allowlist for known false positives"
files = [
  "docs/.*",
  "examples/.*",
  "tests/fixtures/.*",
]
commits = []
paths = []
regexes = [
  # UUIDs or generic hashes in docs
  '''(?i)\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b''',
]

[rules]
# Use built-in default rules from gitleaks

