version: 1
owner: security-engineering

classification:
  tiers:
    - name: high
      description: production credentials, customer data access
      rotate_days: 30
    - name: medium
      description: staging credentials, build tokens
      rotate_days: 60
    - name: low
      description: local/dev credentials
      rotate_days: 90

rotation:
  default_interval_days: 90
  grace_period_days: 7
  notify: true
  notification_channels:
    - slack:#sec-rotations
    - email:security@example.com

requirements:
  storage:
    allowed: ["azure_key_vault", "aws_secrets_manager", "gcp_secret_manager"]
    forbidden: ["repo", "plain_files", "env_only"]
  transport:
    enforce_tls: true
    mTLS_required: true
  access:
    least_privilege: true
    rotation_automation_required: true

audit:
  append_only_ledger: .runs/secrets.jsonl
  fields:
    - timestamp
    - secret_id
    - owner
    - classification
    - rotated_by
    - method
    - notes

