# Gemini CLI Configuration
# This file manages project trust levels and permissions

[projects.'C:\Users\Richard Wilks']
trust_level = "trusted"
enable_git_operations = true
enable_file_operations = true

[projects.'C:\Users\Richard Wilks\CLI_RESTART']
trust_level = "trusted"
enable_git_operations = true
enable_file_operations = true
enable_workflow_execution = true

[projects.'C:\Users\Richard Wilks\cli_multi_rapid_DEV']
trust_level = "trusted"
enable_git_operations = true
enable_file_operations = true

# GitHub Integration Settings
[github]
enabled = true
default_username = "DICKY1987"
api_url = "https://api.github.com"

# Default repositories for quick access
[[github.repositories]]
name = "CLI_RESTART"
owner = "DICKY1987"
default_branch = "main"

[[github.repositories]]
name = "eafix-modular"
owner = "DICKY1987"
default_branch = "main"

# API Configuration
[api]
google_ai_model = "gemini-2.0-flash-exp"
temperature = 0.7
max_tokens = 8192

# Session Management
[sessions]
auto_save = true
keep_history = true
max_history_items = 100
cleanup_days = 30

# Features
[features]
web_search = true
code_execution = true
file_search = true
github_integration = true
workflow_execution = true
