name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  core:
    name: Core tests (Linux, Python 3.11)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-core-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-core-

      - name: Install core test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov coverage rich pyyaml pytest-mock pytest-timeout

      - name: Validate env template covers code vars
        run: |
          python scripts/validate_env.py --check .env.example

      - name: Run core test suite
        env:
          PYTHONPATH: src
        run: |
          pytest -q tests \
            --ignore=tests/benchmarks \
            --ignore=tests/test_websocket_integration.py \
            --ignore=tests/test_enterprise_modules.py \
            --ignore=tests/test_cli_basics_extra.py \
            --cov=src --cov-report=term-missing --cov-fail-under=0

  schemas:
    name: Schema compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run schema compatibility checks
        run: |
          python scripts/check_schema_compatibility.py

  extended:
    name: Extended tests (best-effort)
    runs-on: ubuntu-latest
    needs: core
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-ext-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-ext-

      - name: Install full requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full test suite
        env:
          PYTHONPATH: src
        run: |
          pytest -q tests --cov=src --cov-report=term-missing --maxfail=1

  security:
    name: Security (Bandit + Safety)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-sec-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-sec-

      - name: Install security tooling
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit (SAST)
        run: |
          bandit -r src -x tests -f sarif -o bandit.sarif -lll

      - name: Upload Bandit SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif

      - name: Run Safety (SCA)
        run: |
          if [ -f requirements.txt ]; then REQS="-r requirements.txt"; fi
          safety check $REQS --json > safety.json || export SAFETY_FAILED=$?
          # Fail if Safety found issues
          if [ -n "$SAFETY_FAILED" ]; then
            echo "Safety detected vulnerable dependencies" 1>&2
            exit 1
          fi

      - name: Upload Safety report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: safety.json
          if-no-files-found: warn

  schema-validate:
    name: Schema Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema PyYAML
      - name: Validate schemas
        run: |
          python scripts/validate_schemas.py

  spectral:
    name: OpenAPI Lint (Spectral)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install spectral
        run: |
          npm -g i @stoplight/spectral-cli@6
      - name: Lint OpenAPI specs
        run: |
          spectral lint specs/openapi/**/*.y?(a)ml --fail-severity=error --verbose
