name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-ci:
    name: Run consolidated CI (make ci)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[dev,test]'

      - name: Run consolidated CI
        run: make ci

      - name: Run Bandit (SAST)
        run: |
          bandit -r src -x tests -f sarif -o bandit.sarif -lll

      - name: Upload Bandit SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: bandit.sarif

      - name: Run Safety (SCA)
        run: |
          if [ -f requirements.txt ]; then REQS="-r requirements.txt"; fi
          safety check $REQS --json > safety.json || export SAFETY_FAILED=$?
          # Fail if Safety found issues
          if [ -n "$SAFETY_FAILED" ]; then
            echo "Safety detected vulnerable dependencies" 1>&2
            exit 1
          fi

      - name: Upload Safety report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: safety-report
          path: safety.json
          if-no-files-found: warn

  schema-validate:
    name: Schema Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema PyYAML
      - name: Validate schemas
        run: |
          python scripts/validate_schemas.py

  spectral:
    name: OpenAPI Lint (Spectral)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Install spectral
        run: |
          npm -g i @stoplight/spectral-cli@6
      - name: Lint OpenAPI specs
        run: |
          spectral lint specs/openapi/**/*.y?(a)ml --fail-severity=error --verbose
