name: CLI Orchestrator CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - ".ai/tmp/**"
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -e .
          pip install pre-commit pytest ruff mypy gitleaks
      - name: Pre-commit checks
        run: pre-commit run -a
      - name: Run tests
        run: python -m unittest discover -s tests -v
  cli_orchestrator_test:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install CLI Orchestrator
        run: pip install -e .
      - name: Test CLI Orchestrator
        run: |
          cli-orchestrator --help || true
          python -m cli_multi_rapid.main --help || true
      - name: Validate workflow schemas
        run: |
          python -m jsonschema -i .ai/workflows/PY_EDIT_TRIAGE.yaml .ai/schemas/workflow.schema.json || true
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-orchestrator-artifacts
          path: artifacts/
  cost_reports:
    runs-on: ubuntu-latest
    needs: cli_orchestrator_test
    steps:
      - uses: actions/checkout@v5
      - name: Emit sample token metrics (if missing)
        shell: pwsh
        run: |
          if (-not (Test-Path 'artifacts/tokens.json')) {
            pwsh -NoProfile -File scripts/emit_tokens.ps1 -Out artifacts/tokens.json
          }
      - name: Generate cost reports
        shell: pwsh
        run: |
          pwsh -NoProfile -File scripts/report_costs.ps1 -OutDir artifacts/cost
      - name: Upload cost artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cost-reports
          path: artifacts/cost
      - name: PR summary
        if: ${{ github.event_name == 'pull_request' }}
        shell: pwsh
        run: |
          $p = 'artifacts/cost/cost_report.json'
          if (Test-Path $p) {
            $o = Get-Content -Raw -Path $p | ConvertFrom-Json
            "## Cost Summary`n`n- Total: `$${0}`n- Input tokens: {1}`n- Output tokens: {2}" -f $o.total_cost, $o.effective_input_tokens, $o.output_tokens | Out-File -Encoding utf8 $env:GITHUB_STEP_SUMMARY
          } else {
            "No cost report found." | Out-File -Encoding utf8 $env:GITHUB_STEP_SUMMARY
          }
