name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - ".ai/tmp/**"
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install tooling
        run: |
          pip install pre-commit pytest ruff mypy gitleaks
      - name: Pre-commit checks
        run: pre-commit run -a
      - name: Run tests
        run: pytest -q
  hello_world:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v5
      - name: Run hello world workflow
        shell: pwsh
        run: |
          pwsh -NoProfile -File scripts/run_workflow.ps1 -Name CI
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-artifacts
          path: artifacts/hello_world
