name: Policy Validate

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PowerShell YAML module
        shell: pwsh
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          if (-not (Get-Module -ListAvailable -Name powershell-yaml)) { Install-Module powershell-yaml -Scope CurrentUser -Force }
          Import-Module powershell-yaml -Force
      - name: Validate SLO and Secrets policies
        shell: pwsh
        run: |
          ./scripts/validate_policies.ps1
