name: Reproducible Build
on:
  workflow_dispatch:
  push:
    branches: [ ws/07-testing ]

jobs:
  reproducible:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Verify reproducible build
        run: |
          python scripts/verify_reproducible_build.py