name: Security Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: security-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Secret Scan (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # scan full history

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          # full history
          args: "detect --log-opts=--all --report-format sarif --report-path gitleaks.sarif --redact"

      - name: Upload gitleaks SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

